/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Alex Altuve
 */
public class Administrador extends javax.swing.JFrame {
  Controller control;
  
    /**
     * Creates new form Cliente
     */
   public Administrador() {
        initComponents();
        control= new Controller();
        PrincipalAdmin destino= new PrincipalAdmin();
        control.ConectarPanel(Principal, destino,880, 660, 120, 0);
        control.iniciaVentana(this, "src/Imagenes/LogoPantalla.png"); 
    }
    public Administrador(JTextField user, JTextField Clave) {
        initComponents();
        control= new Controller();
      
        PrincipalAdmin destino= new PrincipalAdmin(user,Clave);
        control.ConectarPanel(Principal, destino,880, 660, 120, 0);
        control.iniciaVentana(this, "src/Imagenes/LogoPantalla.png"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        P1 = new javax.swing.JPanel();
        Admin = new javax.swing.JButton();
        P2 = new javax.swing.JPanel();
        Inventario = new javax.swing.JButton();
        P4 = new javax.swing.JPanel();
        Proveedor = new javax.swing.JButton();
        P5 = new javax.swing.JPanel();
        Ventas = new javax.swing.JButton();
        P3 = new javax.swing.JPanel();
        Produc = new javax.swing.JButton();
        P6 = new javax.swing.JPanel();
        ReponerProduc = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración y Control");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Principal.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 880, 660));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoMain.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 180));

        Salir.setBackground(new java.awt.Color(51, 51, 51));
        Salir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.setToolTipText("");
        Salir.setBorder(null);
        Salir.setBorderPainted(false);
        Salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 110, 40));

        P1.setBackground(new java.awt.Color(255, 255, 255));
        P1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin.setBackground(new java.awt.Color(153, 204, 255));
        Admin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        Admin.setText("Administradores");
        Admin.setToolTipText("");
        Admin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Admin.setContentAreaFilled(false);
        Admin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Admin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AdminMouseMoved(evt);
            }
        });
        Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminMouseExited(evt);
            }
        });
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        P1.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 50));

        P2.setBackground(new java.awt.Color(255, 255, 255));
        P2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inventario.setBackground(new java.awt.Color(153, 204, 255));
        Inventario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario.png"))); // NOI18N
        Inventario.setText("Inventario");
        Inventario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Inventario.setContentAreaFilled(false);
        Inventario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Inventario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                InventarioMouseMoved(evt);
            }
        });
        Inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InventarioMouseExited(evt);
            }
        });
        Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioActionPerformed(evt);
            }
        });
        P2.add(Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 50));

        P4.setBackground(new java.awt.Color(255, 255, 255));
        P4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Proveedor.setBackground(new java.awt.Color(153, 153, 153));
        Proveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedor.png"))); // NOI18N
        Proveedor.setText("Proveedor");
        Proveedor.setBorder(null);
        Proveedor.setContentAreaFilled(false);
        Proveedor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Proveedor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ProveedorMouseMoved(evt);
            }
        });
        Proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProveedorMouseExited(evt);
            }
        });
        Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorActionPerformed(evt);
            }
        });
        P4.add(Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        getContentPane().add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 210, 50));

        P5.setBackground(new java.awt.Color(255, 255, 255));
        P5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ventas.setBackground(new java.awt.Color(153, 153, 255));
        Ventas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Maleta.png"))); // NOI18N
        Ventas.setText("Ventas");
        Ventas.setBorder(null);
        Ventas.setContentAreaFilled(false);
        Ventas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Ventas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                VentasMouseMoved(evt);
            }
        });
        Ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VentasMouseExited(evt);
            }
        });
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });
        P5.add(Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        getContentPane().add(P5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 210, 50));

        P3.setBackground(new java.awt.Color(255, 255, 255));
        P3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Produc.setBackground(new java.awt.Color(102, 153, 255));
        Produc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Produc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Productos.png"))); // NOI18N
        Produc.setText("Agregar Productos");
        Produc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Produc.setContentAreaFilled(false);
        Produc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Produc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ProducMouseMoved(evt);
            }
        });
        Produc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProducMouseExited(evt);
            }
        });
        Produc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducActionPerformed(evt);
            }
        });
        P3.add(Produc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        getContentPane().add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, 50));

        P6.setBackground(new java.awt.Color(255, 255, 255));
        P6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReponerProduc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ReponerProduc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Productos.png"))); // NOI18N
        ReponerProduc.setText("Reponer Productos");
        ReponerProduc.setContentAreaFilled(false);
        ReponerProduc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ReponerProducMouseMoved(evt);
            }
        });
        ReponerProduc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReponerProducMouseExited(evt);
            }
        });
        ReponerProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReponerProducActionPerformed(evt);
            }
        });
        P6.add(ReponerProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        getContentPane().add(P6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 210, 50));

        Regresar.setBackground(new java.awt.Color(51, 204, 255));
        Regresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Regresar.setForeground(new java.awt.Color(255, 255, 255));
        Regresar.setText("Regresar");
        Regresar.setToolTipText("");
        Regresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Regresar.setBorderPainted(false);
        Regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 170, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo blanco.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioActionPerformed
        Inventario destino = new Inventario();
        control.ConectarPanel(Principal, destino,880, 660, 120, 0);
    }//GEN-LAST:event_InventarioActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        AgregarAdministradores destino = new  AgregarAdministradores();
        control.ConectarPanel(Principal, destino,880, 660, 120, 0);
    }//GEN-LAST:event_AdminActionPerformed

    private void ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorActionPerformed
        Proveedor destino = new Proveedor();
        control.ConectarPanel(Principal, destino,880, 660, 120, 0);
    }//GEN-LAST:event_ProveedorActionPerformed

    private void ProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducActionPerformed
        ProductosAgregar destino = new  ProductosAgregar();
        control.ConectarPanel(Principal, destino,880, 660, 120, 0);
    }//GEN-LAST:event_ProducActionPerformed

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
        Ventas destino = new Ventas();
        control.ConectarPanel(Principal, destino,880, 660, 120, 0);
    }//GEN-LAST:event_VentasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        int confirmacion = JOptionPane.showOptionDialog(null,"¿Desea salir del sistema?", "---Confirmación---",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if (confirmacion==0) 
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void AdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseMoved
        P1.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_AdminMouseMoved

    private void AdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseExited
        P1.setBackground(Color.white);
    }//GEN-LAST:event_AdminMouseExited

    private void InventarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventarioMouseMoved
       P2.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_InventarioMouseMoved

    private void InventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventarioMouseExited
         P2.setBackground(Color.white);
    }//GEN-LAST:event_InventarioMouseExited

    private void ProducMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProducMouseMoved
        P3.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_ProducMouseMoved

    private void ProducMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProducMouseExited
        P3.setBackground(Color.white);
    }//GEN-LAST:event_ProducMouseExited

    private void VentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasMouseExited
        P5.setBackground(Color.white);
    }//GEN-LAST:event_VentasMouseExited

    private void ProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProveedorMouseExited
        P4.setBackground(Color.white);
    }//GEN-LAST:event_ProveedorMouseExited

    private void VentasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasMouseMoved
       P5.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_VentasMouseMoved

    private void ProveedorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProveedorMouseMoved
        P4.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_ProveedorMouseMoved

    private void ReponerProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReponerProducActionPerformed
        ProductosReponer destino = new ProductosReponer();
        control.ConectarPanel(Principal, destino,880, 660, 120, 0);
    }//GEN-LAST:event_ReponerProducActionPerformed

    private void ReponerProducMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReponerProducMouseExited
        P6.setBackground(Color.white);
    }//GEN-LAST:event_ReponerProducMouseExited

    private void ReponerProducMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReponerProducMouseMoved
        P6.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_ReponerProducMouseMoved

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
       Login p1 = new Login();
        control.activaVentana(p1, this);
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton Inventario;
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JPanel P3;
    private javax.swing.JPanel P4;
    private javax.swing.JPanel P5;
    private javax.swing.JPanel P6;
    private javax.swing.JPanel Principal;
    private javax.swing.JButton Produc;
    private javax.swing.JButton Proveedor;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton ReponerProduc;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Ventas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
