/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex Altuve
 */
public class AgregarAdministradores extends javax.swing.JPanel {
    Controller control;
    /**
     * Creates new form AgregarAdministradores
     */
    public AgregarAdministradores() {
        initComponents();
        control = new Controller(Nombre,Cedula, Telefono, Direccion,Usuario, Password,Error_Nombre, Error_Cedula, Error_Telefono, Error_Direccion, ListaAdmin);
        control.LlenarArrayListAdminconBD();
        control.LlenarTablaAdmin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaAdmin = new javax.swing.JTable();
        Usuario = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        Agegar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Telefono = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Error_Nombre = new javax.swing.JTextField();
        Error_Cedula = new javax.swing.JTextField();
        Error_Telefono = new javax.swing.JTextField();
        Error_Direccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgrearAdmin.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 60));

        ListaAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Usuario", "Contraseña", "Fecha de Ingreso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaAdmin.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ListaAdmin);
        if (ListaAdmin.getColumnModel().getColumnCount() > 0) {
            ListaAdmin.getColumnModel().getColumn(0).setResizable(false);
            ListaAdmin.getColumnModel().getColumn(1).setResizable(false);
            ListaAdmin.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 800, 230));

        Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioKeyTyped(evt);
            }
        });
        add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 180, 40));

        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordKeyTyped(evt);
            }
        });
        add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 190, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 100, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Usuario");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        Eliminar.setBackground(new java.awt.Color(204, 204, 255));
        Eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 150, 40));

        Agegar.setBackground(new java.awt.Color(204, 204, 255));
        Agegar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Agegar.setText("Agregar");
        Agegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgegarActionPerformed(evt);
            }
        });
        add(Agegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 150, 40));

        Buscar.setBackground(new java.awt.Color(204, 204, 255));
        Buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Buscar.setText("Consultar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 150, 40));

        Modificar.setBackground(new java.awt.Color(204, 204, 255));
        Modificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, 150, 40));

        Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });
        add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 190, 40));

        Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionKeyTyped(evt);
            }
        });
        add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, 40));

        Cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedulaKeyTyped(evt);
            }
        });
        add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 180, 40));

        Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 180, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Elimina.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 70, 60));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modifica.png"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 70, 60));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 70, 60));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarP.png"))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 70, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Teléfono");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Dirección");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cédula");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Password");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        Error_Nombre.setEditable(false);
        Error_Nombre.setBackground(new java.awt.Color(0,0,0,1));
        Error_Nombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Nombre.setBorder(null);
        add(Error_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 180, 10));

        Error_Cedula.setEditable(false);
        Error_Cedula.setBackground(new java.awt.Color(0,0,0,1));
        Error_Cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Cedula.setBorder(null);
        add(Error_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 180, 20));

        Error_Telefono.setEditable(false);
        Error_Telefono.setBackground(new java.awt.Color(0,0,0,1));
        Error_Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Telefono.setBorder(null);
        add(Error_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 190, -1));

        Error_Direccion.setEditable(false);
        Error_Direccion.setBackground(new java.awt.Color(0,0,0,1));
        Error_Direccion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Direccion.setBorder(null);
        add(Error_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 180, 10));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSecundario.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
       control.ConsultarAdministrador();
    }//GEN-LAST:event_BuscarActionPerformed

    private void CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaKeyTyped
      int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
        if (Cedula.getText().trim().length() >=8) {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA la cedula debe tener 6-8 digitos","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_CedulaKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
       int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
        if (Telefono.getText().trim().length() >=11) {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA el telefono debe tener 11 digitos","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }

    }//GEN-LAST:event_TelefonoKeyTyped

    private void UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioKeyTyped

    private void PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordKeyTyped

    private void DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32; 
        boolean numeros= (key >= 48 && key <= 57);
        if (!(minusculas || mayusculas || espacio || numeros)){
        
            JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
           
            evt.consume();
        }
    }//GEN-LAST:event_DireccionKeyTyped

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){
        
            JOptionPane.showMessageDialog(null, "ADVERTENCIA No se aceptan caracteres especiales ni numeros","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
           
            evt.consume();
        }
    }//GEN-LAST:event_NombreKeyTyped

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        control.EliminarAdministrador();
    }//GEN-LAST:event_EliminarActionPerformed

    private void AgegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgegarActionPerformed
       control.AgregarAdministradorBoton();
    }//GEN-LAST:event_AgegarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        control.ModificarAdministrador();
    }//GEN-LAST:event_ModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agegar;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField Cedula;
    private javax.swing.JTextField Direccion;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Error_Cedula;
    private javax.swing.JTextField Error_Direccion;
    private javax.swing.JTextField Error_Nombre;
    private javax.swing.JTextField Error_Telefono;
    private javax.swing.JTable ListaAdmin;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Telefono;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
