/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Alex Altuve
 */
public class Cliente extends javax.swing.JFrame {
 Controller control;
 
    public Cliente() {
        initComponents();
        control= new Controller(Codigo, CodigoCarrito, TotalPagar, ListaProductos, CarritoCompras);
        control.LlenarArrayListconBD();
        control.LlenarTablaProductos(ListaProductos);
        control.iniciaVentana(this, "src/Imagenes/LogoPantalla.png"); 
    }
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        P3 = new javax.swing.JPanel();
        Eliminar = new javax.swing.JButton();
        P1 = new javax.swing.JPanel();
        Agregar = new javax.swing.JButton();
        P2 = new javax.swing.JPanel();
        Comprar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CarritoCompras = new javax.swing.JTable();
        Consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProductos = new javax.swing.JTable();
        Codigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ConsultarCarrrito = new javax.swing.JButton();
        TotalPagar = new javax.swing.JTextField();
        CodigoCarrito = new javax.swing.JTextField();
        VaciarCarrito = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compras de Productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(102, 102, 102));
        Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.setToolTipText("");
        Salir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Salir.setBorderPainted(false);
        Salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, 90, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoMain.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, 180));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Código");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 720, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TituloCompras.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, 60));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 70, 60));

        P3.setBackground(new java.awt.Color(255, 255, 255));
        P3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Elimina.png"))); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setBorder(null);
        Eliminar.setContentAreaFilled(false);
        Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Eliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                EliminarMouseMoved(evt);
            }
        });
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarMouseExited(evt);
            }
        });
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        P3.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        getContentPane().add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 230, 60));

        P1.setBackground(new java.awt.Color(255, 255, 255));
        P1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarCar.png"))); // NOI18N
        Agregar.setText("Agregar");
        Agregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Agregar.setContentAreaFilled(false);
        Agregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Agregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AgregarMouseMoved(evt);
            }
        });
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarMouseExited(evt);
            }
        });
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        P1.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 60));

        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 60));

        P2.setBackground(new java.awt.Color(255, 255, 255));
        P2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Comprar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Comprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Compra.png"))); // NOI18N
        Comprar.setText("Comprar");
        Comprar.setToolTipText("");
        Comprar.setBorder(null);
        Comprar.setContentAreaFilled(false);
        Comprar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Comprar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ComprarMouseMoved(evt);
            }
        });
        Comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ComprarMouseExited(evt);
            }
        });
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });
        P2.add(Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 60));

        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ProductosEnventas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, 60));

        Regresar.setBackground(new java.awt.Color(51, 204, 255));
        Regresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Regresar.setForeground(new java.awt.Color(255, 255, 255));
        Regresar.setText("Regresar");
        Regresar.setToolTipText("");
        Regresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Regresar.setBorderPainted(false);
        Regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 170, 40));

        CarritoCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "                         Nombre", "                         Código", "                         Precio ", "                     Fecha de Vencimiento", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CarritoCompras.setToolTipText("");
        jScrollPane2.setViewportView(CarritoCompras);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 890, 230));

        Consultar.setBackground(new java.awt.Color(255, 204, 153));
        Consultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Consultar.setText("Buscar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 130, 40));

        ListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "                         Nombre", "                         Código", "                         Precio ", "Num.Existencia", "              Fecha de Vencimiento", "                     En oferta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaProductos.setToolTipText("");
        jScrollPane1.setViewportView(ListaProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 930, 210));

        Codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoKeyTyped(evt);
            }
        });
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 170, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TOTAL A PAGAR");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 720, -1, -1));

        ConsultarCarrrito.setBackground(new java.awt.Color(255, 204, 153));
        ConsultarCarrrito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ConsultarCarrrito.setText("Buscar");
        ConsultarCarrrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarCarrritoActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultarCarrrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 710, 120, 40));

        TotalPagar.setEditable(false);
        TotalPagar.setBackground(new java.awt.Color(255, 255, 255));
        TotalPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalPagar.setToolTipText("");
        TotalPagar.setBorder(null);
        getContentPane().add(TotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 710, 110, 30));

        CodigoCarrito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CodigoCarrito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoCarritoKeyTyped(evt);
            }
        });
        getContentPane().add(CodigoCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 710, 170, 40));

        VaciarCarrito.setBackground(new java.awt.Color(204, 204, 255));
        VaciarCarrito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VaciarCarrito.setText("Vaciar Carrito");
        VaciarCarrito.setToolTipText("");
        VaciarCarrito.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        VaciarCarrito.setBorderPainted(false);
        VaciarCarrito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        VaciarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaciarCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(VaciarCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 720, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Código del producto a buscar en Inventario");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSecundario.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1000, 770));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo blanco.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        try{
            String cadena=JOptionPane.showInputDialog(null,"¿Usted ya ha comprado con anterioridad en Soulash? \n\n"+"1. Si\n"+"2.No\n\n");
            if (cadena!=null) {
                int dato= Integer.parseInt(cadena.trim());
                if (dato==1) {
                    String cadena1=JOptionPane.showInputDialog(null,"Introduzca su cedula");
                    if (cadena1!=null) {
                        int cedula= Integer.parseInt(cadena1.trim());   
                          DatosCliente destino = new  DatosCliente(TotalPagar.getText(), control.getListaCarritodeCliente(),cadena1.trim()); // agregado para ver si funcioan el realizarcompra
                          control.activaVentana(destino, this);
                    } 
                } else {
                    if (dato==2) {
                          DatosCliente destino = new  DatosCliente(TotalPagar.getText(), control.getListaCarritodeCliente(),null); // agregado para ver si funcioan el realizarcompra
                          control.activaVentana(destino, this); 
                    } else {
                        JOptionPane.showMessageDialog(null, "ERROR el numero ingresado no esta en el rango 1-2", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);    
                    }
                }
            }
                
        }catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "ADVERTENCIA, no se pueden escribir caracteres en esta opción ", "Warning", JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_ComprarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        int confirmacion = JOptionPane.showOptionDialog(null,"¿Desea salir del sistema?", "---Confirmación---",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if (confirmacion==0) 
          this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        control.AgregaraCarrito();
    }//GEN-LAST:event_AgregarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        control.EliminarProductodeCarrito();
    }//GEN-LAST:event_EliminarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        control.ConsultarInventario(Codigo.getText());
    }//GEN-LAST:event_ConsultarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
       MenuMain p1 = new MenuMain();
       control.activaVentana(p1, this);
    }//GEN-LAST:event_RegresarActionPerformed

    private void AgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseExited
        P1.setBackground(Color.white);
    }//GEN-LAST:event_AgregarMouseExited

    private void AgregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseMoved
        P1.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_AgregarMouseMoved

    private void ComprarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprarMouseExited
        P2.setBackground(Color.white);
    }//GEN-LAST:event_ComprarMouseExited

    private void ComprarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprarMouseMoved
        P2.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_ComprarMouseMoved

    private void EliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseMoved
        P3.setBackground(new java.awt.Color(255,204,204));
    }//GEN-LAST:event_EliminarMouseMoved

    private void EliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseExited
        P3.setBackground(Color.white);
    }//GEN-LAST:event_EliminarMouseExited

    private void ConsultarCarrritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarCarrritoActionPerformed
        control.ConsultarCarrito(CodigoCarrito.getText());
    }//GEN-LAST:event_ConsultarCarrritoActionPerformed

    private void VaciarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaciarCarritoActionPerformed
       control.VaciarCarrito();
    }//GEN-LAST:event_VaciarCarritoActionPerformed

    private void CodigoCarritoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoCarritoKeyTyped
       int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_CodigoCarritoKeyTyped

    private void CodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoKeyTyped
       int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_CodigoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTable CarritoCompras;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField CodigoCarrito;
    private javax.swing.JButton Comprar;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton ConsultarCarrrito;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTable ListaProductos;
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JPanel P3;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField TotalPagar;
    private javax.swing.JButton VaciarCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
