/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex Altuve
 */
public class Inventario extends javax.swing.JPanel {
    Controller control;
    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        control = new Controller(CodigoBuscar, ListaProduc);
        control.LlenarArrayListconBD();
        control.LlenarTablaProductos(ListaProduc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MayorMenor = new javax.swing.JButton();
        MenorMayor = new javax.swing.JButton();
        Reporte = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Consultar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProduc = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        CodigoBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MayorMenor.setBackground(new java.awt.Color(204, 204, 255));
        MayorMenor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MayorMenor.setText("Ordenar Mayor a Menor (Ventas)");
        MayorMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MayorMenorActionPerformed(evt);
            }
        });
        add(MayorMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 260, 50));

        MenorMayor.setBackground(new java.awt.Color(204, 204, 255));
        MenorMayor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MenorMayor.setText("Ordenar Menor a Mayor (Ventas)");
        MenorMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenorMayorActionPerformed(evt);
            }
        });
        add(MenorMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 240, 50));

        Reporte.setBackground(new java.awt.Color(204, 204, 255));
        Reporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Reporte.setText("Generar Reporte ");
        Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteActionPerformed(evt);
            }
        });
        add(Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 140, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Código");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        Consultar.setBackground(new java.awt.Color(255, 204, 153));
        Consultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Consultar.setText("Buscar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 130, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reporte.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 80, 80));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Abajo.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 70, 70));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Arriba.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 60, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 70, 60));

        ListaProduc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Código", "Precio", "Costo", "F. Vencimiento", "N° Lote", "N° Existencia", "Unid. Vendidas", "En Oferta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaProduc.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ListaProduc);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 820, 280));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InventarioTitulo.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 260, 60));

        CodigoBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CodigoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoBuscarActionPerformed(evt);
            }
        });
        CodigoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoBuscarKeyTyped(evt);
            }
        });
        add(CodigoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 170, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSecundario.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
       control.ConsultarInventario(CodigoBuscar.getText());
    }//GEN-LAST:event_ConsultarActionPerformed

    private void ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteActionPerformed
        control.GenerarReporteInventarioPDF();
    }//GEN-LAST:event_ReporteActionPerformed

    private void CodigoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoBuscarActionPerformed

    private void CodigoBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoBuscarKeyTyped
      int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA no se aceptan caracteres especiales ni letras","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_CodigoBuscarKeyTyped

    private void MayorMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MayorMenorActionPerformed
        control.OrdenarMayorMenorPorVentas();
    }//GEN-LAST:event_MayorMenorActionPerformed

    private void MenorMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenorMayorActionPerformed
        control.OrdenarMenorMayorPorVentas();
    }//GEN-LAST:event_MenorMayorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoBuscar;
    private javax.swing.JButton Consultar;
    private javax.swing.JTable ListaProduc;
    private javax.swing.JButton MayorMenor;
    private javax.swing.JButton MenorMayor;
    private javax.swing.JButton Reporte;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
