/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex Altuve
 */
public class MenuMain extends javax.swing.JFrame {
    Controller control;
    /**
     * Creates new form PantallaPrincipal
     */
    public MenuMain() {
        initComponents();
        control= new Controller();
        control.iniciaVentana(this, "src/Imagenes/LogoPantalla.png"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        P1 = new javax.swing.JPanel();
        Administrador = new javax.swing.JButton();
        P2 = new javax.swing.JPanel();
        Cliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal - Soulash");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ubicacion1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 90, 70));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Titulo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 460, 140));

        Salir.setBackground(new java.awt.Color(204, 204, 255));
        Salir.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        Salir.setText("Salir");
        Salir.setBorder(null);
        Salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 100, 40));

        P1.setBackground(new java.awt.Color(255, 255, 255));
        P1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Administrador.setBackground(new java.awt.Color(255, 204, 204));
        Administrador.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        Administrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Admin.png"))); // NOI18N
        Administrador.setText("ADMINISTRADOR");
        Administrador.setActionCommand("");
        Administrador.setBorder(null);
        Administrador.setContentAreaFilled(false);
        Administrador.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AdministradorMouseMoved(evt);
            }
        });
        Administrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdministradorMouseExited(evt);
            }
        });
        Administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministradorActionPerformed(evt);
            }
        });
        P1.add(Administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 50));

        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 280, 50));

        P2.setBackground(new java.awt.Color(255, 255, 255));
        P2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cliente.setBackground(new java.awt.Color(153, 204, 255));
        Cliente.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        Cliente.setText("CLIENTE");
        Cliente.setActionCommand("");
        Cliente.setBorder(null);
        Cliente.setContentAreaFilled(false);
        Cliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Cliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ClienteMouseMoved(evt);
            }
        });
        Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClienteMouseExited(evt);
            }
        });
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        P2.add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 50));

        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 280, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ints.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 360, 130));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bs. As. Argentina");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 220, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ws.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 390, 130));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoMain.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 180));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSecundario.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 550, 550));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo blanco.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        Cliente p1 = new Cliente();
        control.activaVentana(p1, this );
    }//GEN-LAST:event_ClienteActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        int confirmacion = JOptionPane.showOptionDialog(null,"¿Desea salir del sistema?", "---Confirmación---",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if (confirmacion==0) 
          this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void AdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministradorActionPerformed
        Login p1 = new Login();
        control.activaVentana(p1, this);
    }//GEN-LAST:event_AdministradorActionPerformed

    private void AdministradorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministradorMouseExited
        P1.setBackground(Color.white);
    }//GEN-LAST:event_AdministradorMouseExited

    private void AdministradorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministradorMouseMoved
        P1.setBackground(new java.awt.Color(255,204,204));
    }//GEN-LAST:event_AdministradorMouseMoved

    private void ClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClienteMouseExited
        P2.setBackground(Color.white);
    }//GEN-LAST:event_ClienteMouseExited

    private void ClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClienteMouseMoved
       P2.setBackground(new java.awt.Color(153,204,255));
    }//GEN-LAST:event_ClienteMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Administrador;
    private javax.swing.JButton Cliente;
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
