/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.Controller;
import javax.swing.JTextField;

/**
 *
 * @author Windows10
 */
public class PrincipalAdmin extends javax.swing.JPanel {
    Controller control;
    /**
     * Creates new form PrincipalAdmin
     */
    public PrincipalAdmin(JTextField user, JTextField clave) {
        initComponents();
        control = new Controller(UsuarioEntro);
        control.LlenarArrayListAdminconBD();
        control.LLenarSaludo(user,clave);
       
    }
    public PrincipalAdmin() {
        initComponents();
        control = new Controller(UsuarioEntro);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneles3 = new Model.Paneles();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        paneles1 = new Model.Paneles();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Panel2 = new Model.Paneles();
        UsuarioEntro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        paneles2 = new Model.Paneles();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneles3.setBackground(new java.awt.Color(255, 255, 255));
        paneles3.setRoundBottomLeft(60);
        paneles3.setRoundBottomRight(60);
        paneles3.setRoundTopLeft(60);
        paneles3.setRoundTopRight(60);
        paneles3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Publicidad1.png"))); // NOI18N
        paneles3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 160));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.png"))); // NOI18N
        paneles3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 220, 210));

        add(paneles3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 220, 380));

        paneles1.setBackground(new java.awt.Color(255, 255, 255));
        paneles1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        paneles1.setRoundBottomLeft(60);
        paneles1.setRoundBottomRight(60);
        paneles1.setRoundTopLeft(60);
        paneles1.setRoundTopRight(60);
        paneles1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Publicidad2.png"))); // NOI18N
        paneles1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 170));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        paneles1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 220, 210));

        add(paneles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, 370));

        Panel2.setBackground(new java.awt.Color(255, 255, 255));
        Panel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Panel2.setRoundBottomLeft(50);
        Panel2.setRoundBottomRight(50);
        Panel2.setRoundTopLeft(50);
        Panel2.setRoundTopRight(50);
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsuarioEntro.setEditable(false);
        UsuarioEntro.setBackground(new java.awt.Color(255, 255, 255));
        UsuarioEntro.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        UsuarioEntro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UsuarioEntro.setBorder(null);
        UsuarioEntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioEntroActionPerformed(evt);
            }
        });
        Panel2.add(UsuarioEntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 370, 60));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("B    I    E    N    V     E    N   I    D    O ");
        Panel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 440, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Perfil.png"))); // NOI18N
        Panel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 130, 100));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPan.png"))); // NOI18N
        Panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 190, 170));

        add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 780, 170));

        paneles2.setBackground(new java.awt.Color(255, 255, 255));
        paneles2.setRoundBottomLeft(60);
        paneles2.setRoundBottomRight(60);
        paneles2.setRoundTopLeft(60);
        paneles2.setRoundTopRight(60);
        paneles2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Publicidad3.png"))); // NOI18N
        paneles2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 140));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/F3.png"))); // NOI18N
        paneles2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 210));

        add(paneles2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 220, 380));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSecundario.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioEntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioEntroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioEntroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Model.Paneles Panel2;
    private javax.swing.JTextField UsuarioEntro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private Model.Paneles paneles1;
    private Model.Paneles paneles2;
    private Model.Paneles paneles3;
    // End of variables declaration//GEN-END:variables
}
