/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.Controller;

/**
 *
 * @author Windows10
 */
public class ProductosReponer extends javax.swing.JPanel {
      Controller control;
    /**
     * Creates new form ProductosReponer
     */
    public ProductosReponer() {
        initComponents();
        control = new Controller(Reponer);
        control.LlenarArrayListconBD();
        control. MenoraMayorExistencia();
         control.LlenarRegistroProveedorBD();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Reponer = new javax.swing.JTable();
        ReponerInventario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ProductoUnid.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarP.png"))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 70, 60));

        Reponer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Código", "Precio", "Costo", "F. Vencimiento", "N° Lote", "N° Existencia", "Unid. Vendidas", "En Oferta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Reponer.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Reponer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 820, 360));

        ReponerInventario.setBackground(new java.awt.Color(204, 204, 255));
        ReponerInventario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ReponerInventario.setText("Reponer Inventario");
        ReponerInventario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ReponerInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReponerInventarioActionPerformed(evt);
            }
        });
        add(ReponerInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 160, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSecundario.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void ReponerInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReponerInventarioActionPerformed
     
        control.ReponerProductos();
    }//GEN-LAST:event_ReponerInventarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Reponer;
    private javax.swing.JButton ReponerInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
