/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;

/**
 *
 * @author Alex Altuve
 */
public class Ventas extends javax.swing.JPanel {
    Controller control;
    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        control = new Controller();
        control.LlenarControllerVentas(ListaVentas);
        control.LlenarArrayHistorialVentasBD();
        control.LLenarTablaHistorialVentas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaVentas = new javax.swing.JTable();
        MayorVenta = new javax.swing.JButton();
        MenorVenta = new javax.swing.JButton();
        GenerarReporte = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ventas.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 450, 70));

        ListaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "N° Factura", "Total Pagado", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaVentas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ListaVentas);
        if (ListaVentas.getColumnModel().getColumnCount() > 0) {
            ListaVentas.getColumnModel().getColumn(0).setResizable(false);
            ListaVentas.getColumnModel().getColumn(1).setResizable(false);
            ListaVentas.getColumnModel().getColumn(2).setResizable(false);
            ListaVentas.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 810, 340));

        MayorVenta.setBackground(new java.awt.Color(204, 204, 255));
        MayorVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MayorVenta.setText("Ver de Mayor a Menor Venta");
        MayorVenta.setBorder(null);
        MayorVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MayorVentaActionPerformed(evt);
            }
        });
        add(MayorVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 200, 40));

        MenorVenta.setBackground(new java.awt.Color(204, 204, 255));
        MenorVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MenorVenta.setText("Ver de Menor a Mayor Venta");
        MenorVenta.setBorder(null);
        MenorVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenorVentaActionPerformed(evt);
            }
        });
        add(MenorVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 200, 40));

        GenerarReporte.setBackground(new java.awt.Color(204, 204, 255));
        GenerarReporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GenerarReporte.setText("Generar Reporte");
        GenerarReporte.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        GenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarReporteActionPerformed(evt);
            }
        });
        add(GenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 130, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reporte.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 80, 80));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Abajo.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 70, 70));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Arriba.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 60, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSecundario.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void MayorVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MayorVentaActionPerformed
       control.VerMayor();
    }//GEN-LAST:event_MayorVentaActionPerformed

    private void MenorVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenorVentaActionPerformed
       control.VerMenor();
    }//GEN-LAST:event_MenorVentaActionPerformed

    private void GenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarReporteActionPerformed
        control.GenerarReporteVentasPDF();

    }//GEN-LAST:event_GenerarReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerarReporte;
    private javax.swing.JTable ListaVentas;
    private javax.swing.JButton MayorVenta;
    private javax.swing.JButton MenorVenta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
